# Generated by Django 3.0.2 on 2020-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snakecategories',
            options={'verbose_name': 'Categories'},
        ),
    ]
